-- MySQL Script generated by MySQL Workbench
-- Sat Oct 31 15:10:07 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `caiadoapp` DEFAULT CHARACTER SET utf8 ;
USE `caiadoapp` ;

-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`cliente` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cliente_nome` VARCHAR(90) NOT NULL,
  `cliente_cpf` VARCHAR(14) NOT NULL,
  `cliente_datanascimento` DATETIME NOT NULL,
  `cliente_sexo` CHAR(1) NOT NULL,
  `cliente_telefone` VARCHAR(11) NOT NULL,
  `cliente_celular` VARCHAR(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario_cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`usuario_cliente` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`usuario_cliente` (
  `cliente_id` INT NOT NULL,
  `usuario_cliente_email` VARCHAR(45) NOT NULL,
  `usuario_cliente_senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cliente_id`),
  CONSTRAINT `fk_usuario_cliente_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `caiadoapp`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`fornecedor` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`fornecedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fornecedor_nome` VARCHAR(45) NOT NULL,
  `fornecedor_cnpj` VARCHAR(17) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`produto` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`produto` (
  `produto_id` INT NOT NULL AUTO_INCREMENT,
  `produto_nome` VARCHAR(45) BINARY NOT NULL,
  `produto_preco` DOUBLE UNSIGNED NOT NULL,
  `fornecedor_id` INT NOT NULL,
  PRIMARY KEY (`produto_id`),
  INDEX `fk_produto_fornecedor1_idx` (`fornecedor_id` ASC),
  CONSTRAINT `fk_produto_fornecedor1`
    FOREIGN KEY (`fornecedor_id`)
    REFERENCES `caiadoapp`.`fornecedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carrinho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`carrinho` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`carrinho` (
  `cliente_id` INT NOT NULL,
  `carrinho_valortotal` DOUBLE NOT NULL,
  `carrinho_valorentrega` DOUBLE NOT NULL,
  `carrinho_valor_produtos` DOUBLE NOT NULL,
  `carrinho_observacoes` VARCHAR(455) NULL,
  `metodo_entrega_id` INT NOT NULL,
  INDEX `fk_carrinho_metodo_entrega1_idx` (`metodo_entrega_id` ASC),
  CONSTRAINT `fk_carrinho_cliente2`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `caiadoapp`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrinho_metodo_entrega1`
    FOREIGN KEY (`metodo_entrega_id`)
    REFERENCES `caiadoapp`.`metodo_entrega` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`metodo_entrega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`metodo_entrega` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`metodo_entrega` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `metodp_entrega_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carrinho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`carrinho` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`carrinho` (
  `cliente_id` INT NOT NULL,
  `carrinho_valortotal` DOUBLE NOT NULL,
  `carrinho_valorentrega` DOUBLE NOT NULL,
  `carrinho_valor_produtos` DOUBLE NOT NULL,
  `carrinho_observacoes` VARCHAR(455) NULL,
  `metodo_entrega_id` INT NOT NULL,
  INDEX `fk_carrinho_metodo_entrega1_idx` (`metodo_entrega_id` ASC),
  CONSTRAINT `fk_carrinho_cliente2`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `caiadoapp`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrinho_metodo_entrega1`
    FOREIGN KEY (`metodo_entrega_id`)
    REFERENCES `caiadoapp`.`metodo_entrega` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`estado` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`estado` (
  `id` INT NOT NULL AUTO_INCREMENT AUTO_INCREMENT,
  `estado_nome` VARCHAR(45) NOT NULL,
  `estado_uf` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`cidade` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cidade_nome` VARCHAR(60) NOT NULL,
  `estado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cidade_estado1_idx` (`estado_id` ASC),
  CONSTRAINT `fk_cidade_estado1`
    FOREIGN KEY (`estado_id`)
    REFERENCES `caiadoapp`.`estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`endereco` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `endereco_logradouro` VARCHAR(70) NOT NULL,
  `endereco_bairro` VARCHAR(60) NOT NULL,
  `endereco_numero` INT NOT NULL,
  `endereco_cep` VARCHAR(10) NOT NULL,
  `cidade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_endereco_cidade1_idx` (`cidade_id` ASC),
  CONSTRAINT `fk_endereco_cidade1`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `caiadoapp`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Loja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`Loja` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`Loja` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `loja_cpnj` VARCHAR(17) NOT NULL,
  `loja_realizaservico` TINYINT NOT NULL,
  `loja_numero` INT NOT NULL,
  `endereco_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Loja_endereco1_idx` (`endereco_id` ASC),
  CONSTRAINT `fk_Loja_endereco1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `caiadoapp`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`Estoque` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`Estoque` (
  `Loja_id` INT NOT NULL,
  `recurso_recurso_id` INT NOT NULL,
  `loja_estoque_quantidade` INT NOT NULL,
  INDEX `fk_Estoque_recurso1_idx` (`recurso_recurso_id` ASC),
  CONSTRAINT `fk_Estoque_Loja1`
    FOREIGN KEY (`Loja_id`)
    REFERENCES `caiadoapp`.`Loja` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estoque_recurso1`
    FOREIGN KEY (`recurso_recurso_id`)
    REFERENCES `caiadoapp`.`produto` (`produto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`pedido` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`pedido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `endereco_id` INT NOT NULL,
  `metodo_entrega_id` INT NOT NULL,
  `status_pedido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pedido_endereco1_idx` (`endereco_id` ASC),
  INDEX `fk_pedido_metodo_entrega1_idx` (`metodo_entrega_id` ASC),
  CONSTRAINT `fk_pedido_endereco1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `caiadoapp`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_metodo_entrega1`
    FOREIGN KEY (`metodo_entrega_id`)
    REFERENCES `caiadoapp`.`metodo_entrega` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`venda` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`venda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `venda_valortotal` DOUBLE NOT NULL,
  `venda_notafiscal` INT NOT NULL,
  `venda_data` DATETIME NOT NULL,
  `venda_totaldesconto` DOUBLE NOT NULL,
  `venda_valor_entrega` DOUBLE NOT NULL,
  `venda_icms` DOUBLE NULL,
  `venda_ipi` DOUBLE NULL,
  `venda_iss` DOUBLE NULL,
  `venda_pagamento` VARCHAR(45) NOT NULL,
  `cliente_id` INT NOT NULL,
  `pedido_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_venda_cliente1_idx` (`cliente_id` ASC),
  INDEX `fk_venda_pedido1_idx` (`pedido_id` ASC),
  CONSTRAINT `fk_venda_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `caiadoapp`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_pedido1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `caiadoapp`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tarefa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`tarefa` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`tarefa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tarefa_data_inicio` DATETIME NOT NULL,
  `tarefa_data_fim` DATETIME NOT NULL,
  `tarefa_nfs` INT NOT NULL,
  `venda_id` INT NOT NULL,
  INDEX `fk_tarefa_venda1_idx` (`venda_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tarefa_venda1`
    FOREIGN KEY (`venda_id`)
    REFERENCES `caiadoapp`.`venda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`servico` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`servico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `servico_nome` VARCHAR(45) NOT NULL,
  `servico_preco` DOUBLE NOT NULL,
  `servico_duracao` TIME NOT NULL,
  `tarefa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_servico_tarefa1_idx` (`tarefa_id` ASC),
  CONSTRAINT `fk_servico_tarefa1`
    FOREIGN KEY (`tarefa_id`)
    REFERENCES `caiadoapp`.`tarefa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto_carrinho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`produto_carrinho` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`produto_carrinho` (
  `carrinho_cliente_id` INT NOT NULL,
  `produto_produto_id` INT NOT NULL,
  `qtde` INT NOT NULL,
  INDEX `fk_produto_carrinho_produto1_idx` (`produto_produto_id` ASC),
  CONSTRAINT `fk_produto_carrinho_carrinho1`
    FOREIGN KEY (`carrinho_cliente_id`)
    REFERENCES `caiadoapp`.`carrinho` (`cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_carrinho_produto1`
    FOREIGN KEY (`produto_produto_id`)
    REFERENCES `caiadoapp`.`produto` (`produto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`endereco_cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`endereco_cliente` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`endereco_cliente` (
  `cliente_id` INT NOT NULL,
  `endereco_id` INT NOT NULL,
  INDEX `fk_endereco_cliente_endereco1_idx` (`endereco_id` ASC),
  CONSTRAINT `fk_endereco_cliente_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `caiadoapp`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_cliente_endereco1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `caiadoapp`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venda_servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`venda_servico` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`venda_servico` (
  `venda_id` INT NOT NULL,
  `servico_id` INT NOT NULL,
  INDEX `fk_venda_servico_servico1_idx` (`servico_id` ASC),
  CONSTRAINT `fk_venda_servico_venda1`
    FOREIGN KEY (`venda_id`)
    REFERENCES `caiadoapp`.`venda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_servico_servico1`
    FOREIGN KEY (`servico_id`)
    REFERENCES `caiadoapp`.`servico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venda_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`venda_produto` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`venda_produto` (
  `venda_id` INT NOT NULL,
  `produto_produto_id` INT NOT NULL,
  INDEX `fk_venda_servico_produto1_idx` (`produto_produto_id` ASC),
  CONSTRAINT `fk_venda_servico_venda2`
    FOREIGN KEY (`venda_id`)
    REFERENCES `caiadoapp`.`venda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_servico_produto1`
    FOREIGN KEY (`produto_produto_id`)
    REFERENCES `caiadoapp`.`produto` (`produto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ordem_compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`ordem_compra` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`ordem_compra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pedido_id` INT NOT NULL,
  `ordem_compra_notafiscal` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ordem_compra_pedido1_idx` (`pedido_id` ASC),
  CONSTRAINT `fk_ordem_compra_pedido1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `caiadoapp`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`compra` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`compra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ordem_compra_id` INT NOT NULL,
  `compra_valortotal` DOUBLE NOT NULL,
  `compra_notafiscal` INT NOT NULL,
  `compra_icms` INT NOT NULL,
  `fornecedor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_compra_ordem_compra1_idx` (`ordem_compra_id` ASC),
  INDEX `fk_compra_fornecedor1_idx` (`fornecedor_id` ASC),
  CONSTRAINT `fk_compra_ordem_compra1`
    FOREIGN KEY (`ordem_compra_id`)
    REFERENCES `caiadoapp`.`ordem_compra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_fornecedor1`
    FOREIGN KEY (`fornecedor_id`)
    REFERENCES `caiadoapp`.`fornecedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`fatura` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`fatura` (
  `fatura_valor` DOUBLE NOT NULL,
  `venda_id` INT NULL,
  `compra_id` INT NULL,
  INDEX `fk_fatura_venda1_idx` (`venda_id` ASC),
  INDEX `fk_fatura_compra1_idx` (`compra_id` ASC),
  CONSTRAINT `fk_fatura_venda1`
    FOREIGN KEY (`venda_id`)
    REFERENCES `caiadoapp`.`venda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fatura_compra1`
    FOREIGN KEY (`compra_id`)
    REFERENCES `caiadoapp`.`compra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto_compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`produto_compra` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`produto_compra` (
  `produto_produto_id` INT NOT NULL,
  `compra_id` INT NOT NULL,
  `produto_compra_qtde` INT NOT NULL,
  INDEX `fk_produto_has_compra_compra1_idx` (`compra_id` ASC),
  INDEX `fk_produto_has_compra_produto1_idx` (`produto_produto_id` ASC),
  CONSTRAINT `fk_produto_has_compra_produto1`
    FOREIGN KEY (`produto_produto_id`)
    REFERENCES `caiadoapp`.`produto` (`produto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_has_compra_compra1`
    FOREIGN KEY (`compra_id`)
    REFERENCES `caiadoapp`.`compra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carrinho_servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`carrinho_servico` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`carrinho_servico` (
  `carrinho_cliente_id` INT NOT NULL,
  `servico_id` INT NOT NULL,
  INDEX `fk_carrinho_has_servico_servico1_idx` (`servico_id` ASC),
  INDEX `fk_carrinho_has_servico_carrinho1_idx` (`carrinho_cliente_id` ASC),
  CONSTRAINT `fk_carrinho_has_servico_carrinho1`
    FOREIGN KEY (`carrinho_cliente_id`)
    REFERENCES `caiadoapp`.`carrinho` (`cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrinho_has_servico_servico1`
    FOREIGN KEY (`servico_id`)
    REFERENCES `caiadoapp`.`servico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`favoritos_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`favoritos_produto` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`favoritos_produto` (
  `cliente_id` INT NOT NULL,
  `produto_produto_id` INT NOT NULL,
  INDEX `fk_cliente_has_produto_produto1_idx` (`produto_produto_id` ASC),
  INDEX `fk_cliente_has_produto_cliente1_idx` (`cliente_id` ASC) ,
  CONSTRAINT `fk_cliente_has_produto_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `caiadoapp`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_produto_produto1`
    FOREIGN KEY (`produto_produto_id`)
    REFERENCES `caiadoapp`.`produto` (`produto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`favoritos_servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`favoritos_servico` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`favoritos_servico` (
  `cliente_id` INT NOT NULL,
  `servico_id` INT NOT NULL,
  INDEX `fk_cliente_has_servico_servico1_idx` (`servico_id` ASC) ,
  INDEX `fk_cliente_has_servico_cliente1_idx` (`cliente_id` ASC) ,
  CONSTRAINT `fk_cliente_has_servico_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `caiadoapp`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_servico_servico1`
    FOREIGN KEY (`servico_id`)
    REFERENCES `caiadoapp`.`servico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`marca` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`marca` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marca_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`veiculo` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`veiculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `veiculo_nome` VARCHAR(45) NOT NULL,
  `veiculo_anofabricacao` INT NOT NULL,
  `veiculo_quilometragem` INT NOT NULL,
  `marca_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_veiculo_marca1_idx` (`marca_id` ASC) ,
  CONSTRAINT `fk_veiculo_marca1`
    FOREIGN KEY (`marca_id`)
    REFERENCES `caiadoapp`.`marca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`veiculo_cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`veiculo_cliente` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`veiculo_cliente` (
  `veiculo_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  INDEX `fk_veiculo_has_cliente_cliente1_idx` (`cliente_id` ASC) ,
  INDEX `fk_veiculo_has_cliente_veiculo1_idx` (`veiculo_id` ASC) ,
  CONSTRAINT `fk_veiculo_has_cliente_veiculo1`
    FOREIGN KEY (`veiculo_id`)
    REFERENCES `caiadoapp`.`veiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_veiculo_has_cliente_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `caiadoapp`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`administrador` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`administrador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `administrador_nome` VARCHAR(45) NOT NULL,
  `administrador_cpf` VARCHAR(14) NOT NULL,
  `administrador_datanascimento` DATE NOT NULL,
  `administrador_sexo` CHAR(1) NOT NULL,
  `administrador_telefone` VARCHAR(15) NOT NULL,
  `administrador_celular` VARCHAR(15) NOT NULL,
  `administrador_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sac`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`sac` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`sac` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sac_titulo` VARCHAR(45) NOT NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sac_cliente1_idx` (`cliente_id` ASC) ,
  CONSTRAINT `fk_sac_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `caiadoapp`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario_administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`usuario_administrador` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`usuario_administrador` (
  `administrador_id` INT NOT NULL,
  `ativo` TINYINT NOT NULL,
  `administrador_usuario` VARCHAR(45) NOT NULL,
  `administrador_senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`administrador_id`),
  CONSTRAINT `fk_usuario_administrador_administrador1`
    FOREIGN KEY (`administrador_id`)
    REFERENCES `caiadoapp`.`administrador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mensagem_administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`mensagem_administrador` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`mensagem_administrador` (
  `mensagem_id` VARCHAR(45) NOT NULL,
  `sac_id` INT NOT NULL,
  `mensagem_conteudo` VARCHAR(455) NOT NULL,
  `mensagem_datahora` DATETIME NOT NULL,
  `usuario_administrador_administrador_id` INT NOT NULL,
  INDEX `fk_mensagem_sac1_idx` (`sac_id` ASC) ,
  PRIMARY KEY (`mensagem_id`),
  INDEX `fk_mensagem_administrador_usuario_administrador1_idx` (`usuario_administrador_administrador_id` ASC),
  CONSTRAINT `fk_mensagem_sac1`
    FOREIGN KEY (`sac_id`)
    REFERENCES `caiadoapp`.`sac` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mensagem_administrador_usuario_administrador1`
    FOREIGN KEY (`usuario_administrador_administrador_id`)
    REFERENCES `caiadoapp`.`usuario_administrador` (`administrador_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`administrador_endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`administrador_endereco` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`administrador_endereco` (
  `administrador_id` INT NOT NULL,
  `endereco_id` INT NOT NULL,
  INDEX `fk_administrador_has_endereco_endereco1_idx` (`endereco_id` ASC) ,
  INDEX `fk_administrador_has_endereco_administrador1_idx` (`administrador_id` ASC),
  CONSTRAINT `fk_administrador_has_endereco_administrador1`
    FOREIGN KEY (`administrador_id`)
    REFERENCES `caiadoapp`.`administrador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_administrador_has_endereco_endereco1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `caiadoapp`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mensagem_cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`mensagem_cliente` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`mensagem_cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mensagemcliente_conteudo` VARCHAR(455) NOT NULL,
  `mensagemcliente_datahora` VARCHAR(45) NOT NULL,
  `sac_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mensagem_cliente_sac1_idx` (`sac_id` ASC) ,
  INDEX `fk_mensagem_cliente_cliente1_idx` (`cliente_id` ASC) ,
  CONSTRAINT `fk_mensagem_cliente_sac1`
    FOREIGN KEY (`sac_id`)
    REFERENCES `caiadoapp`.`sac` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mensagem_cliente_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `caiadoapp`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`historico_administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`historico_administrador` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`historico_administrador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `historico_administradordescricao` VARCHAR(45) NOT NULL,
  `administrador_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_historico_administrador_administrador1_idx` (`administrador_id` ASC),
  CONSTRAINT `fk_historico_administrador_administrador1`
    FOREIGN KEY (`administrador_id`)
    REFERENCES `caiadoapp`.`administrador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`historico_cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`historico_cliente` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`historico_cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `historico_clientedescricao` VARCHAR(45) NOT NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_historico_cliente_cliente1_idx` (`cliente_id` ASC) ,
  CONSTRAINT `fk_historico_cliente_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `caiadoapp`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`agenda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`agenda` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`agenda` (
  `Loja_id` INT NOT NULL,
  `tarefa_id` INT NOT NULL,
  INDEX `fk_agenda_Loja1_idx` (`Loja_id` ASC) ,
  INDEX `fk_agenda_tarefa1_idx` (`tarefa_id` ASC) ,
  CONSTRAINT `fk_agenda_Loja1`
    FOREIGN KEY (`Loja_id`)
    REFERENCES `caiadoapp`.`Loja` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agenda_tarefa1`
    FOREIGN KEY (`tarefa_id`)
    REFERENCES `caiadoapp`.`tarefa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`imagem_servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`imagem_servico` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`imagem_servico` (
  `imagem_servico_1` LONGBLOB NOT NULL,
  `imagem_servico_2` LONGBLOB NOT NULL,
  `servico_id` INT NOT NULL,
  INDEX `fk_imagem_servico_servico1_id` (`servico_id` ASC) ,
  CONSTRAINT `fk_imagem_servico_servico1`
    FOREIGN KEY (`servico_id`)
    REFERENCES `caiadoapp`.`servico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`imagem_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caiadoapp`.`imagem_produto` ;

CREATE TABLE IF NOT EXISTS `caiadoapp`.`imagem_produto` (
  `imagem_produto_1` LONGBLOB NOT NULL,
  `imagem_produto_2` LONGBLOB NOT NULL,
  `produto_produto_id` INT NOT NULL,
  INDEX `fk_imagem_produto_produto_idx` (`produto_produto_id` ASC) ,
  CONSTRAINT `fk_imagem_produto_produto1`
    FOREIGN KEY (`produto_produto_id`)
    REFERENCES `caiadoapp`.`produto` (`produto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE `caiadoapp`.`usuario_administrador` 
ADD COLUMN `administrador_nivel` INT NOT NULL AFTER `administrador_senha`;

ALTER TABLE `caiadoapp`.`usuario_administrador` 
CHANGE COLUMN `ativo` `usuario_administrador_ativo` TINYINT NOT NULL ,
CHANGE COLUMN `administrador_usuario` `usuario_administrador_usuario` VARCHAR(45) NOT NULL ,
CHANGE COLUMN `administrador_senha` `usuario_administrador_senha` VARCHAR(45) NOT NULL ,
CHANGE COLUMN `administrador_nivel` `usuario_administrador_nivel` INT NOT NULL ,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`administrador_id`, `usuario_administrador_usuario`);
;

ALTER TABLE `caiadoapp`.`usuario_administrador` 
ADD UNIQUE INDEX `usuario_administrador_usuario_UNIQUE` (`usuario_administrador_usuario` ASC) VISIBLE;
;

ALTER TABLE `caiadoapp`.`usuario_cliente` 
ADD UNIQUE INDEX `usuario_cliente_email_UNIQUE` (`usuario_cliente_email` ASC) VISIBLE;
;

ALTER TABLE `caiadoapp`.`api_tokens` 
DROP FOREIGN KEY `user_id`;
ALTER TABLE `caiadoapp`.`api_tokens` 
CHANGE COLUMN `user_id` `user_id` INT NOT NULL ,
ADD INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
DROP PRIMARY KEY;
;
ALTER TABLE `caiadoapp`.`api_tokens` 
ADD CONSTRAINT `user_id`
  FOREIGN KEY (`user_id`)
  REFERENCES `caiadoapp`.`cliente` (`id`);

ALTER TABLE `caiadoapp`.`api_tokens` 
ADD PRIMARY KEY (`user_id`);

ALTER TABLE `caiadoapp`.`marca` 
ADD UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE;
;

ALTER TABLE `caiadoapp`.`marca` 
ADD COLUMN `marca_datacriacao` DATETIME NULL AFTER `marca_nome`,
ADD COLUMN `marca_dataatualizacao` DATETIME NULL AFTER `marca_datacriacao`;

ALTER TABLE `caiadoapp`.`veiculo` 
ADD COLUMN `veiculo_ativo` TINYINT NOT NULL AFTER `marca_id`;

ALTER TABLE `caiadoapp`.`veiculo` 
ADD UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE;
;

INSERT INTO `caiadoapp`.`marca` (`marca_nome`) VALUES ('Chevrolet');
INSERT INTO `caiadoapp`.`marca` (`marca_nome`) VALUES ('Ford');
INSERT INTO `caiadoapp`.`marca` (`marca_nome`) VALUES ('Renault');
INSERT INTO `caiadoapp`.`marca` (`marca_nome`) VALUES ('Nissan');
INSERT INTO `caiadoapp`.`marca` (`marca_nome`) VALUES ('Fiat');
INSERT INTO `caiadoapp`.`marca` (`marca_nome`) VALUES ('Volkswagen');
INSERT INTO `caiadoapp`.`marca` (`marca_nome`) VALUES ('Toyota');
INSERT INTO `caiadoapp`.`marca` (`marca_nome`) VALUES ('Hyundai');
INSERT INTO `caiadoapp`.`marca` (`marca_nome`) VALUES ('Jeep');
INSERT INTO `caiadoapp`.`marca` (`marca_nome`) VALUES ('Citroën');
INSERT INTO `caiadoapp`.`marca` (`marca_nome`) VALUES ('Mitsubishi');
INSERT INTO `caiadoapp`.`marca` (`marca_nome`) VALUES ('Peugeot');
INSERT INTO `caiadoapp`.`marca` (`marca_nome`) VALUES ('Chery');
INSERT INTO `caiadoapp`.`marca` (`marca_nome`) VALUES ('BMW');
INSERT INTO `caiadoapp`.`marca` (`marca_nome`) VALUES ('Mercedes-Benz');
INSERT INTO `caiadoapp`.`marca` (`marca_nome`) VALUES ('Kia');
INSERT INTO `caiadoapp`.`marca` (`marca_nome`) VALUES ('Audi');
INSERT INTO `caiadoapp`.`marca` (`marca_nome`) VALUES ('Volvo');
INSERT INTO `caiadoapp`.`marca` (`marca_nome`) VALUES ('Land Rover');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
